refactor: 상품 및 꿀조합 검색 결과 API 페이징 방식 변경
fun-eat/funeat-server pull request #11
Opened 2024-01-15 04:18 UTC by Go-Jaecheol

## Issue

- close #7 

## ✨ 구현한 기능

`상품 검색 결과 API`, `꿀조합 검색 결과 API`
AS-IS : Offset 기반 페이지네이션
TO-BE : Cursor 기반 페이지네이션

+
`꿀조합 검색 결과`:  id 오름차순 정렬 -> 내림차순 정렬로 변경

## 📢 논의하고 싶은 내용

X

## 🎸 기타

X

## ⏰ 일정

- 추정 시간 : 1h
- 걸린 시간 : 2h

2024-01-15 05:46 UTC, wugawuga requested changes
충돌나는 코드만 수정부탁드려용

2024-01-15 05:46 UTC, wugawuga commented on src/main/java/com/funeat/product/application/ProductService.java
> +        final boolean hasNext = products.size() > DEFAULT_PAGE_SIZE;
코틀린 문법인가여?

2024-01-15 05:46 UTC, wugawuga commented on src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            final var response = 상품_검색_결과_조회_요청("망고", 0L);
첫 아이디를 받는거라서 FIRST_PAGE 제거한건가요?

2024-01-18 09:30 UTC, Go-Jaecheol commented on src/main/java/com/funeat/product/application/ProductService.java
> +        final boolean hasNext = products.size() > DEFAULT_PAGE_SIZE;
자바 문법인데 혹시 17로 버전 올려서 그런가여?!

근데 그것보다 이거 로직상 잘못된 거 같은데 뭔가 이상하지 않나요..?
다시 한 번 봐야겠네요,,

2024-01-18 09:31 UTC, Go-Jaecheol commented on src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            final var response = 상품_검색_결과_조회_요청("망고", 0L);
FIRST_PAGE는 이름이 안맞는 거 같아서 바꿨는데, 얘도 상수로 빼버릴까요??

2024-01-18 11:06 UTC, wugawuga commented on src/main/java/com/funeat/product/application/ProductService.java
> +        final boolean hasNext = products.size() > DEFAULT_PAGE_SIZE;
로직은 잘못된지 잘 모르겠어용
변수 = 조건식
이렇게 들어가는 건 처음 보는거 같아서용

2024-01-18 11:07 UTC, wugawuga commented on src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            final var response = 상품_검색_결과_조회_요청("망고", 0L);
그대로 가도 될 거 같아요

2024-01-20 15:53 UTC, Go-Jaecheol commented
hasNext 구하는 과정이 잘못됐었네요,, 한 번 더 확인 안했으면 놓칠뻔

기존에 다른 메서드에서 사용중인 `getResultSize()`, `hasNextPage()` 메서드 활용해서 수정했습니다!
수정하는 김에 검증 테스트도 더 추가했어요
`ProductService`에서는 파라미터 타입만 바꿔서 쓰면 돼서 해당 메서드들 제네릭 사용했는데,
`RecipeService`에 있는 기존 `hasNextPage()`는 Page를 파라미터로 받고 있어서 `.getContent()` 때문에 하나 새로 만들었어요.

이거 전에 머지된 상품 자동 완성 부분 로직도 수정해야 되는데, 이거 머지되면 수정해서 새로 PR 올릴게여

2024-01-20 15:53 UTC, Go-Jaecheol commented on src/main/java/com/funeat/product/application/ProductService.java
> +        final boolean hasNext = products.size() > DEFAULT_PAGE_SIZE;
로직 잘못됐어서 수정했어용

2024-01-23 11:13 UTC, merged