refactor: 꿀조합에 사용된 상품 정보에 상품 이미지 URL 추가
fun-eat/funeat-server pull request #27
Opened 2024-03-27 13:52 UTC by 70825

## Issue

- close #26 

## ✨ 구현한 기능

![image](https://github.com/fun-eat/funeat-server/assets/79046106/49185564-f598-4762-b156-cab30dc7892d)

- 꿀조합에 사용된 상품들의 이미지 URL을 추가했습니다.
  - 하리보 짜파게티 → 하리보 상품 사진 경로, 짜파게티 상품 사진 경로를 가지고 있음

- 새로 DTO를 만들어서 작업 했습니다.
  - 기존 상품 정보 DTO가 쓰이는 곳
    - 꿀조합 검색
    - 상품에서 볼 수 있는 꿀조합
    - 레시피 목록
    - 레시피 상세 정보

## 📢 논의하고 싶은 내용

.

## 🎸 기타

.

## ⏰ 일정

- 추정 시간 : 1
- 걸린 시간 : 1

2024-03-27 14:06 UTC, 70825 commented on src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +            단일_리뷰_저장(review3);
저장 순서 보장이 안되서 에러가 발생하기 때문에 일단 `단일_리뷰_저장(...)`으로 교체 했습니다.

2024-04-02 09:35 UTC, Go-Jaecheol requested changes
고생하셨습니다!!
코멘트 2개 남겨놨으니 확인해주세요~~

2024-04-02 09:35 UTC, Go-Jaecheol commented on src/main/java/com/funeat/recipe/dto/DetailProductRecipeDto.java
> +
여기 줄바꿈은 없어도 될 것 같아요!

2024-04-02 09:35 UTC, Go-Jaecheol commented on src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +import com.funeat.recipe.dto.*;
저희 컨벤션에 import 와일드카드 사용 안하는 걸로 되어있지 않나요..??

2024-04-02 10:27 UTC, 70825 commented on src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +import com.funeat.recipe.dto.*;
엇 노트북 포맷하면서 인텔리제이 설정을 안해뒀네요 수정했습니다~

2024-04-02 10:35 UTC, 70825 commented on src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +            단일_리뷰_저장(review3);
이거 이렇게 해도 테스트 실패가 나와서 롤백할게요~

2024-04-02 11:20 UTC, wugawuga approved these changes

2024-04-02 11:22 UTC, Go-Jaecheol approved these changes

2024-04-03 01:17 UTC, merged