refactor: 꿀조합 랭킹 API 수정
fun-eat/funeat-server pull request #38
Opened 2024-04-07 14:27 UTC by Go-Jaecheol

## Issue

- close #37 

## ✨ 구현한 기능

- 꿀조합 랭킹 API response 수정
  - 반환 데이터 3개 -> 4개
  - author : 객체 -> String
  - favoriteCount -> favorite(boolean)

- 로그인 한 사용자는 favorite에 자신이 누른 좋아요 여부 / 로그인 안한 사용자는 favorite 전부 false로 반환

- 관련 서비스 테스트 수정 및 추가

## 📢 논의하고 싶은 내용

X

## 🎸 기타

- 로그인 여부에 상관없이 모두 API 접근이 가능해야 하기 때문에 해당 API 경로에 대한 인터셉터랑 전체 ArgumentResolver 로직 수정했습니다. 
  (우선은 로그인 안한 경우 게스트를 나타내는 LoginInfo 반환하도록 수정)

## ⏰ 일정

- 추정 시간 : 1h
- 걸린 시간 : 2h

2024-04-08 04:10 UTC, 70825 requested changes
인수 테스트에 로그인된 상태로 테스트하는거 하나 추가하고 자잘한거 수정하면 완벽한 것 같아요~
혹시 제가 놓친게 있을지도 모르니 수정하면 다시 리뷰 요청 보내주세요

2024-04-08 04:10 UTC, 70825 commented on src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +        class 로그인_여부_응답_테스트 {
👍👍👍

2024-04-08 04:10 UTC, 70825 commented on src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
> +    private final Boolean favoriteCount;
이거 이름을 `favorite`로 바꿔야할 것 같아요~

2024-04-08 04:10 UTC, 70825 commented on src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +        void 전체_꿀조합들_중에서_랭킹_TOP4를_조회할_수_있다() {
인수 테스트도 비로그인, 로그인 사용자 둘 다 구분해서 테스트하는게 더 좋을 것 같아요

2024-04-08 04:10 UTC, 70825 commented on src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +                final var loginId = -1L;
[AS-IS]
```java
    @Nested
    class getTop3Recipes_성공_테스트 {
```

[TO-BE]
```java
    @Nested
    class getTop4Recipes_성공_테스트 {
```

2024-04-19 06:15 UTC, Go-Jaecheol commented on src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
> +    private final Boolean favoriteCount;
favorite으로 바꾸고 author 타입 다시 바꿔달라고 해서 author만 롤백했슴다

2024-04-19 06:16 UTC, Go-Jaecheol commented on src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +        void 전체_꿀조합들_중에서_랭킹_TOP4를_조회할_수_있다() {
조회 요청할 때 쿠키 담을 수 있도록 오버로딩 하고, 로그인 여부에 따라 테스트 2개로 분리했습니다~

2024-04-19 06:20 UTC, 70825 approved these changes
커밋이 순서대로 있어서 편하게 코드 읽었네요 더 수정할 부분은 없어보여요 고생하셨슴다 👍👍

2024-04-19 06:26 UTC, merged