feat: 태그 검색 구현
fun-eat/funeat-server pull request #71
Opened 2024-06-02 04:47 UTC by wugawuga

- 상품의 태그 Top3 중 있으면 검색해서 조회

## Issue

- close #60 

## ✨ 구현한 기능

- 상품들이 가지고 있는 리뷰중에서 Top3 태그로만 검색이 되게 구현했습니다.

2024-06-02 11:12 UTC, 70825 requested changes
우가 고생하셨어요~
쿼리문에 궁금한 점이 있어서 코멘트 남깁니다~

### 1. 상품의 태그 Top3 중 있으면 검색해서 조회

`상품의 태그 TOP 3`이라는 뜻은 상품에서 가장 많이 언급된 태그 3개를 말하는거죠??

제가 이해하는게 맞다면 아래 테스트 코드는 통과하지 말아야 하는데 통과하고 있어요

```
product1에 달린 태그
단짠단짠: 3회
맛있어요: 3회
갓성비: 2회
간식: 1회
```

```java
        @Test
        void 간식_태그는_4위이므로_검색되지_말아야한다() {
            // given
            final var category = 카테고리_간편식사_생성();
            단일_카테고리_저장(category);

            final var 태그_맛있어요 = 태그_맛있어요_TASTE_생성();
            final var 태그_단짠단짠 = 태그_맛있어요_TASTE_생성();
            final var 태그_갓성비 = 태그_맛있어요_TASTE_생성();
            final var 태그_간식 = 태그_간식_ETC_생성();

            final var 태그1 = 단일_태그_저장(태그_맛있어요);
            final var 태그2 = 단일_태그_저장(태그_단짠단짠);
            final var 태그3 = 단일_태그_저장(태그_갓성비);
            final var 태그4 = 단일_태그_저장(태그_간식);

            final var product1 = 상품_애플망고_가격3000원_평점5점_생성(category);
            final var product2 = 상품_망고빙수_가격5000원_평점4점_생성(category);
            final var product3 = 상품_망고빙수_가격5000원_평점4점_생성(category);
            final var product4 = 상품_망고빙수_가격5000원_평점4점_생성(category);
            복수_상품_저장(product1, product2, product3, product4);

            final var member1 = 멤버_멤버1_생성();
            final var member2 = 멤버_멤버2_생성();
            복수_멤버_저장(member1, member2);

            final var review1_1 = 리뷰_이미지test1_평점1점_재구매X_생성(member1, product1, 0L);
            final var review1_2 = 리뷰_이미지test5_평점5점_재구매O_생성(member2, product1, 0L);
            final var review2_1 = 리뷰_이미지test3_평점3점_재구매O_생성(member1, product2, 0L);
            복수_리뷰_저장(review1_1, review1_2, review2_1);

            복수_리뷰_태그_저장(
                    리뷰태그_생성(review1_1, 태그_맛있어요),
                    리뷰태그_생성(review1_1, 태그_맛있어요),
                    리뷰태그_생성(review1_1, 태그_단짠단짠),
                    리뷰태그_생성(review1_1, 태그_단짠단짠),
                    리뷰태그_생성(review1_1, 태그_갓성비),
                    리뷰태그_생성(review1_1, 태그_갓성비),
                    리뷰태그_생성(review1_1, 태그_간식),
                    리뷰태그_생성(review1_1, 태그_맛있어요),
                    리뷰태그_생성(review1_2, 태그_단짠단짠),
                    리뷰태그_생성(review2_1, 태그_맛있어요)
            );

            final var expected = List.of(product1);

            // when
            final var actual = productRepository.searchProductsByTopTagsFirst(태그4, PageRequest.of(0, 10));

            // then
            assertThat(actual).usingRecursiveComparison()
                    .isEqualTo(expected);
        }
```

### 2. 쿼리문에서 궁금한 점

`searchProductsByTopTagsFirst` 쿼리문입니다

```
                "   WHERE rt2.tag.id = :tagId AND rt2.tag.id IN ( " +
                "       SELECT rt3.tag.id FROM Review r3 " +
                "       JOIN r3.reviewTags rt3 " +
                "       WHERE r3.product.id = p2.id " +
                "       GROUP BY rt3.tag.id " +
                "       ORDER BY COUNT(rt3.tag.id) DESC " +
                "   ) " +
```

1) 위 서브쿼리문은 상품에 검색한 태그가 있어야 한다는거죠?? 이게 맞으면 상품에 적용된 상위 3개 태그를 확인하는게 맞는 것 같은데 `LIMIT 3`이 언급되는 부분이 없어서요. 거기다가 `LIMIT 3`이 없으면 `ORDER BY COUNT(rt3.tag.id) DESC`는 필요 없는 쿼리문으로 보여요

```
                "   WHERE rt2.tag.id = :tagId AND rt2.tag.id IN ( .... )" +
                "   GROUP BY p2.id " +
                "   HAVING COUNT(DISTINCT rt2.tag.id) <= 3 " +
```

2) 위 쿼리문에서 `HAVING COUNT(DISTINCT rt2.tag.id) <= 3`은 `특정 태그는 3개 이하여야 한다`라는 쿼리문인데, 의미 없는 쿼리문으로 보여서요.
왜냐하면 `WHERE rt2.tag.id = :tagId`로 인해서 tagId인 태그만 감지되는 상황이라 `(상품1, 리뷰1, 태그1), (상품1, 리뷰2, 태그1), (상품1, 리뷰3, 태그1), ...`로 태그1을 포함하는 데이터들만 나오게 되는데요. 이때 `DISTINCT rt2.tag.id`는 `rt2.tag.id 적용 -> (태그1), (태그1), (태그1), ... -> DISTINCT 적용 -> (태그1)`로 데이터 1개만 나오기 때문에 `HAVING COUNT(DISTINCT rt2.tag.id) <= 3`은 곧 `1 <= 3`이라서 무조건 참인 쿼리문이라서요.

제가 이해한게 맞다면 쿼리문 자체를 다시 수정해야 할 것 같습니다

2024-06-02 11:12 UTC, 70825 commented on src/main/java/com/funeat/product/persistence/ProductRepositoryImpl.java
> +public class ProductRepositoryImpl implements ProductRepositoryCustom {
여기에서도 전부 final 붙이면 좋아보입니다~

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +                    .isEqualTo(expected2);
이거는 `SoftAssertions`으로 한 번에 합치는게 좋아보여요

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +            final var product4 = 상품_망고빙수_가격5000원_평점4점_생성(category);
`product3`이랑 `product4`는 둘 다 태그도 없고, 사용되지 않는 변수이기 때문에 사실상 같은 역할이라 `product4`는 제거해도 될 것 같아요

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +            final var 태그_갓성비 = 태그_맛있어요_TASTE_생성();
이 부분이랑 `특정_태그와_마지막_상품아이디_이후_상품들을_조회한다` 테스트 모두 이름에 맞는 태그로 변경하는게 더 정확해보여요

```suggestion
            final var 태그_맛있어요 = 태그_맛있어요_TASTE_생성();
            final var 태그_단짠단짠 = 태그_단짠단짠_TASTE_생성();
            final var 태그_갓성비 = 태그_갓성비_PRICE_생성();
```

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +import static com.funeat.acceptance.product.ProductSteps.*;
와일드카드 제거해주세요 ~

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +import static com.funeat.fixture.TagFixture.*;
여기도 와일드카드 제거해주세요~

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/acceptance/product/ProductSteps.java
> +                .then().log().all()
`log().all()` 삭제해주세요~

2024-06-02 11:12 UTC, 70825 commented on src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    List<Product> findAllByTag(@Param("tagId") final Long tagId, @Param("lastId") final Long lastId, final Pageable pageable);
이 코드는 사용되지 않고 있는데 추가되는게 맞나요?

2024-06-02 11:12 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +    class findAllByTagFirst_성공_테스트 {
`findAllByTagFirst`는 서비스 메서드라 이름을 바꾸고, 2개 테스트 클래스로 나눠야 할 것 같아요

2024-06-03 07:54 UTC, wugawuga commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +    class findAllByTagFirst_성공_테스트 {
이게 어떤 말씀일까용?

2024-06-03 07:54 UTC, wugawuga commented on src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    List<Product> findAllByTag(@Param("tagId") final Long tagId, @Param("lastId") final Long lastId, final Pageable pageable);
삭제했습니다

2024-06-04 01:38 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +    class findAllByTagFirst_성공_테스트 {
아아 서비스 메서드 이름이랑 같은줄 알았네요
리포지토리 테스트에 맞게 `searchProductsByTopTagsFirst`랑 `searchProductsByTopTags`로 클래스를 나누는게 좋아보여요

2024-06-04 01:38 UTC, 70825 commented on src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +            final var 태그_갓성비 = 태그_맛있어요_TASTE_생성();
이거 아직 수정 안됐어요~

2024-06-04 01:38 UTC, 70825 commented on src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +import static com.funeat.acceptance.product.ProductSteps.*;
여기도 아직 수정 안됐어요~

2024-06-04 01:49 UTC, 70825 approved these changes
우가 고생하셨어요 
쿼리문에 `"""`로 하니까 확실히 보기 편하네요 👍👍
간단한 부분 수정하고 머지하면 될 것 같아서 미리 Approve 하겠습니다 ~

2024-06-04 01:49 UTC, 70825 commented on src/main/java/com/funeat/product/persistence/ProductRepositoryImpl.java
> +                """;
```suggestion
        final String jpql = """
                SELECT DISTINCT p 
                FROM Product p 
                WHERE p.id IN ( 
                    SELECT p2.id 
                    FROM Product p2 
                    JOIN p2.reviews r2 
                    JOIN r2.reviewTags rt2 
                    WHERE rt2.tag.id = :tagId 
                      AND rt2.tag.id IN ( 
                          SELECT rt3.tag.id 
                          FROM Review r3 
                          JOIN r3.reviewTags rt3 
                          WHERE r3.product.id = p2.id 
                          GROUP BY rt3.tag.id 
                          ORDER BY COUNT(rt3.tag.id) DESC 
                          LIMIT 3 
                      ) 
                ) 
                ORDER BY p.id DESC
                """;
```

여기에 `\s`를 사용한 이유가 있나요?? 문제 있는게 아니라면 그냥 스페이스바로 수정하는게 더 코드 보기 편한 것 같아요

2024-06-06 07:59 UTC, 70825 approved these changes
LGTM 👍👍

2024-06-07 10:55 UTC, Go-Jaecheol approved these changes
👍👍

2024-06-07 10:55 UTC, merged